// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface AddSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.AddSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool added = 1;</code>
   * @return The added.
   */
  boolean getAdded();
}
