// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

/**
 * Protobuf type {@code com.subscriptionmanager.CreateGenreRequest}
 */
public final class CreateGenreRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.subscriptionmanager.CreateGenreRequest)
    CreateGenreRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateGenreRequest.newBuilder() to construct.
  private CreateGenreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateGenreRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateGenreRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.subscription.proto.Message.internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.subscription.proto.Message.internal_static_com_subscriptionmanager_CreateGenreRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.subscription.proto.CreateGenreRequest.class, com.subscription.proto.CreateGenreRequest.Builder.class);
  }

  public static final int GENRE_FIELD_NUMBER = 1;
  private com.subscription.proto.Genre genre_;
  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the genre field is set.
   */
  @java.lang.Override
  public boolean hasGenre() {
    return genre_ != null;
  }
  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The genre.
   */
  @java.lang.Override
  public com.subscription.proto.Genre getGenre() {
    return genre_ == null ? com.subscription.proto.Genre.getDefaultInstance() : genre_;
  }
  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.subscription.proto.GenreOrBuilder getGenreOrBuilder() {
    return getGenre();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (genre_ != null) {
      output.writeMessage(1, getGenre());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (genre_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGenre());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.subscription.proto.CreateGenreRequest)) {
      return super.equals(obj);
    }
    com.subscription.proto.CreateGenreRequest other = (com.subscription.proto.CreateGenreRequest) obj;

    if (hasGenre() != other.hasGenre()) return false;
    if (hasGenre()) {
      if (!getGenre()
          .equals(other.getGenre())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGenre()) {
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + getGenre().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.subscription.proto.CreateGenreRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscription.proto.CreateGenreRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.subscription.proto.CreateGenreRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscription.proto.CreateGenreRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.subscription.proto.CreateGenreRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.subscriptionmanager.CreateGenreRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.subscriptionmanager.CreateGenreRequest)
      com.subscription.proto.CreateGenreRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_CreateGenreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subscription.proto.CreateGenreRequest.class, com.subscription.proto.CreateGenreRequest.Builder.class);
    }

    // Construct using com.subscription.proto.CreateGenreRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (genreBuilder_ == null) {
        genre_ = null;
      } else {
        genre_ = null;
        genreBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor;
    }

    @java.lang.Override
    public com.subscription.proto.CreateGenreRequest getDefaultInstanceForType() {
      return com.subscription.proto.CreateGenreRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.subscription.proto.CreateGenreRequest build() {
      com.subscription.proto.CreateGenreRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.subscription.proto.CreateGenreRequest buildPartial() {
      com.subscription.proto.CreateGenreRequest result = new com.subscription.proto.CreateGenreRequest(this);
      if (genreBuilder_ == null) {
        result.genre_ = genre_;
      } else {
        result.genre_ = genreBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.subscription.proto.CreateGenreRequest) {
        return mergeFrom((com.subscription.proto.CreateGenreRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.subscription.proto.CreateGenreRequest other) {
      if (other == com.subscription.proto.CreateGenreRequest.getDefaultInstance()) return this;
      if (other.hasGenre()) {
        mergeGenre(other.getGenre());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGenreFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.subscription.proto.Genre genre_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.subscription.proto.Genre, com.subscription.proto.Genre.Builder, com.subscription.proto.GenreOrBuilder> genreBuilder_;
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the genre field is set.
     */
    public boolean hasGenre() {
      return genreBuilder_ != null || genre_ != null;
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The genre.
     */
    public com.subscription.proto.Genre getGenre() {
      if (genreBuilder_ == null) {
        return genre_ == null ? com.subscription.proto.Genre.getDefaultInstance() : genre_;
      } else {
        return genreBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setGenre(com.subscription.proto.Genre value) {
      if (genreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        genre_ = value;
        onChanged();
      } else {
        genreBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setGenre(
        com.subscription.proto.Genre.Builder builderForValue) {
      if (genreBuilder_ == null) {
        genre_ = builderForValue.build();
        onChanged();
      } else {
        genreBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeGenre(com.subscription.proto.Genre value) {
      if (genreBuilder_ == null) {
        if (genre_ != null) {
          genre_ =
            com.subscription.proto.Genre.newBuilder(genre_).mergeFrom(value).buildPartial();
        } else {
          genre_ = value;
        }
        onChanged();
      } else {
        genreBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearGenre() {
      if (genreBuilder_ == null) {
        genre_ = null;
        onChanged();
      } else {
        genre_ = null;
        genreBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.subscription.proto.Genre.Builder getGenreBuilder() {
      
      onChanged();
      return getGenreFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.subscription.proto.GenreOrBuilder getGenreOrBuilder() {
      if (genreBuilder_ != null) {
        return genreBuilder_.getMessageOrBuilder();
      } else {
        return genre_ == null ?
            com.subscription.proto.Genre.getDefaultInstance() : genre_;
      }
    }
    /**
     * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.subscription.proto.Genre, com.subscription.proto.Genre.Builder, com.subscription.proto.GenreOrBuilder> 
        getGenreFieldBuilder() {
      if (genreBuilder_ == null) {
        genreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.subscription.proto.Genre, com.subscription.proto.Genre.Builder, com.subscription.proto.GenreOrBuilder>(
                getGenre(),
                getParentForChildren(),
                isClean());
        genre_ = null;
      }
      return genreBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.subscriptionmanager.CreateGenreRequest)
  }

  // @@protoc_insertion_point(class_scope:com.subscriptionmanager.CreateGenreRequest)
  private static final com.subscription.proto.CreateGenreRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.subscription.proto.CreateGenreRequest();
  }

  public static com.subscription.proto.CreateGenreRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateGenreRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateGenreRequest>() {
    @java.lang.Override
    public CreateGenreRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateGenreRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateGenreRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.subscription.proto.CreateGenreRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

