// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface CreateGenreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.CreateGenreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the genre field is set.
   */
  boolean hasGenre();
  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The genre.
   */
  com.subscription.proto.Genre getGenre();
  /**
   * <code>.com.subscriptionmanager.Genre genre = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.subscription.proto.GenreOrBuilder getGenreOrBuilder();
}
