// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface CreateSubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.CreateSubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the subscription field is set.
   */
  boolean hasSubscription();
  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The subscription.
   */
  com.subscription.proto.Subscription getSubscription();
  /**
   * <code>.com.subscriptionmanager.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.subscription.proto.SubscriptionOrBuilder getSubscriptionOrBuilder();
}
