// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface GenreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.Genre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string subscription_uid = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The subscriptionUid.
   */
  java.lang.String getSubscriptionUid();
  /**
   * <code>string subscription_uid = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for subscriptionUid.
   */
  com.google.protobuf.ByteString
      getSubscriptionUidBytes();

  /**
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
