// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_News_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_News_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateNewsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateNewsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_Genre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_Genre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateGenreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_AddSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_AddSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_AddSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_AddSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_RenewSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_RenewSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_Newsletter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_Newsletter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_NewsletterMailInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_NewsletterMailInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_subscriptionmanager_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_subscriptionmanager_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\027com.subscriptionmanager" +
      "\032\037google/api/field_behavior.proto\"]\n\004New" +
      "s\022\017\n\002id\030\001 \001(\tB\003\340A\003\022\026\n\tgenre_uid\030\002 \001(\tB\003\340" +
      "A\002\022\022\n\005title\030\003 \001(\tB\003\340A\002\022\030\n\013description\030\004 " +
      "\001(\tB\003\340A\002\"E\n\021CreateNewsRequest\0220\n\004news\030\001 " +
      "\001(\0132\035.com.subscriptionmanager.NewsB\003\340A\002\"" +
      "J\n\005Genre\022\017\n\002id\030\001 \001(\tB\003\340A\003\022\035\n\020subscriptio" +
      "n_uid\030\002 \001(\tB\003\340A\002\022\021\n\004name\030\003 \001(\tB\003\340A\002\"H\n\022C" +
      "reateGenreRequest\0222\n\005genre\030\001 \001(\0132\036.com.s" +
      "ubscriptionmanager.GenreB\003\340A\002\"]\n\014Subscri" +
      "ption\022\017\n\002id\030\001 \001(\tB\003\340A\003\022\021\n\004name\030\002 \001(\tB\003\340A" +
      "\002\022\022\n\005price\030\003 \001(\rB\003\340A\002\022\025\n\010validity\030\004 \001(\rB" +
      "\003\340A\002\"]\n\031CreateSubscriptionRequest\022@\n\014sub" +
      "scription\030\001 \001(\0132%.com.subscriptionmanage" +
      "r.SubscriptionB\003\340A\002\"0\n\027ListSubscriptionR" +
      "equest\022\025\n\010user_uid\030\001 \001(\tB\003\340A\002\"X\n\030ListSub" +
      "scriptionResponse\022<\n\rsubscriptions\030\001 \003(\013" +
      "2%.com.subscriptionmanager.Subscription\"" +
      "N\n\026AddSubscriptionRequest\022\025\n\010user_uid\030\001 " +
      "\001(\tB\003\340A\002\022\035\n\020subscription_uid\030\002 \001(\tB\003\340A\002\"" +
      "(\n\027AddSubscriptionResponse\022\r\n\005added\030\001 \001(" +
      "\010\"Q\n\031DeleteSubscriptionRequest\022\025\n\010user_u" +
      "id\030\001 \001(\tB\003\340A\002\022\035\n\020subscription_uid\030\002 \001(\tB" +
      "\003\340A\002\"-\n\032DeleteSubscriptionResponse\022\017\n\007de" +
      "leted\030\001 \001(\010\"P\n\030RenewSubscriptionRequest\022" +
      "\025\n\010user_uid\030\001 \001(\tB\003\340A\002\022\035\n\020subscription_u" +
      "id\030\002 \001(\tB\003\340A\002\",\n\031RenewSubscriptionRespon" +
      "se\022\017\n\007renewed\030\001 \001(\010\"\315\001\n\004User\022\017\n\002id\030\001 \001(\t" +
      "B\003\340A\003\022\021\n\004name\030\002 \001(\tB\003\340A\002\022\025\n\010email_id\030\003 \001" +
      "(\tB\003\340A\002\022\025\n\010password\030\004 \001(\tB\003\340A\002\0225\n\004role\030\005" +
      " \001(\0162\".com.subscriptionmanager.User.Role" +
      "B\003\340A\002\"<\n\004Role\022\024\n\020ROLE_UNSPECIFIED\020\000\022\r\n\tR" +
      "OLE_USER\020\001\022\017\n\013ROLE_WRITER\020\002\"E\n\021CreateUse" +
      "rRequest\0220\n\004user\030\001 \001(\0132\035.com.subscriptio" +
      "nmanager.UserB\003\340A\002\"\032\n\nNewsletter\022\014\n\004news" +
      "\030\001 \003(\t\"^\n\022NewsletterMailInfo\0227\n\nnewslett" +
      "er\030\001 \001(\0132#.com.subscriptionmanager.Newsl" +
      "etter\022\017\n\007emailId\030\002 \003(\t\"\007\n\005EmptyB\032\n\026com.s" +
      "ubscription.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
        });
    internal_static_com_subscriptionmanager_News_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_subscriptionmanager_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_News_descriptor,
        new java.lang.String[] { "Id", "GenreUid", "Title", "Description", });
    internal_static_com_subscriptionmanager_CreateNewsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_subscriptionmanager_CreateNewsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateNewsRequest_descriptor,
        new java.lang.String[] { "News", });
    internal_static_com_subscriptionmanager_Genre_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_subscriptionmanager_Genre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_Genre_descriptor,
        new java.lang.String[] { "Id", "SubscriptionUid", "Name", });
    internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_subscriptionmanager_CreateGenreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateGenreRequest_descriptor,
        new java.lang.String[] { "Genre", });
    internal_static_com_subscriptionmanager_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_subscriptionmanager_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_Subscription_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "Validity", });
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_subscriptionmanager_CreateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_subscriptionmanager_ListSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListSubscriptionRequest_descriptor,
        new java.lang.String[] { "UserUid", });
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_subscriptionmanager_ListSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_ListSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscriptions", });
    internal_static_com_subscriptionmanager_AddSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_subscriptionmanager_AddSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_AddSubscriptionRequest_descriptor,
        new java.lang.String[] { "UserUid", "SubscriptionUid", });
    internal_static_com_subscriptionmanager_AddSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_subscriptionmanager_AddSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_AddSubscriptionResponse_descriptor,
        new java.lang.String[] { "Added", });
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_DeleteSubscriptionRequest_descriptor,
        new java.lang.String[] { "UserUid", "SubscriptionUid", });
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_DeleteSubscriptionResponse_descriptor,
        new java.lang.String[] { "Deleted", });
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_subscriptionmanager_RenewSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_RenewSubscriptionRequest_descriptor,
        new java.lang.String[] { "UserUid", "SubscriptionUid", });
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_subscriptionmanager_RenewSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_RenewSubscriptionResponse_descriptor,
        new java.lang.String[] { "Renewed", });
    internal_static_com_subscriptionmanager_User_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_subscriptionmanager_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_User_descriptor,
        new java.lang.String[] { "Id", "Name", "EmailId", "Password", "Role", });
    internal_static_com_subscriptionmanager_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_subscriptionmanager_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_subscriptionmanager_Newsletter_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_subscriptionmanager_Newsletter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_Newsletter_descriptor,
        new java.lang.String[] { "News", });
    internal_static_com_subscriptionmanager_NewsletterMailInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_subscriptionmanager_NewsletterMailInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_NewsletterMailInfo_descriptor,
        new java.lang.String[] { "Newsletter", "EmailId", });
    internal_static_com_subscriptionmanager_Empty_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_subscriptionmanager_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_subscriptionmanager_Empty_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
