// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface NewsletterMailInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.NewsletterMailInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.subscriptionmanager.Newsletter newsletter = 1;</code>
   * @return Whether the newsletter field is set.
   */
  boolean hasNewsletter();
  /**
   * <code>.com.subscriptionmanager.Newsletter newsletter = 1;</code>
   * @return The newsletter.
   */
  com.subscription.proto.Newsletter getNewsletter();
  /**
   * <code>.com.subscriptionmanager.Newsletter newsletter = 1;</code>
   */
  com.subscription.proto.NewsletterOrBuilder getNewsletterOrBuilder();

  /**
   * <code>repeated string emailId = 2;</code>
   * @return A list containing the emailId.
   */
  java.util.List<java.lang.String>
      getEmailIdList();
  /**
   * <code>repeated string emailId = 2;</code>
   * @return The count of emailId.
   */
  int getEmailIdCount();
  /**
   * <code>repeated string emailId = 2;</code>
   * @param index The index of the element to return.
   * @return The emailId at the given index.
   */
  java.lang.String getEmailId(int index);
  /**
   * <code>repeated string emailId = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the emailId at the given index.
   */
  com.google.protobuf.ByteString
      getEmailIdBytes(int index);
}
