// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface NewsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.News)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string genre_uid = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The genreUid.
   */
  java.lang.String getGenreUid();
  /**
   * <code>string genre_uid = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for genreUid.
   */
  com.google.protobuf.ByteString
      getGenreUidBytes();

  /**
   * <code>string title = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
