// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface NewsletterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.Newsletter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string news = 1;</code>
   * @return A list containing the news.
   */
  java.util.List<java.lang.String>
      getNewsList();
  /**
   * <code>repeated string news = 1;</code>
   * @return The count of news.
   */
  int getNewsCount();
  /**
   * <code>repeated string news = 1;</code>
   * @param index The index of the element to return.
   * @return The news at the given index.
   */
  java.lang.String getNews(int index);
  /**
   * <code>repeated string news = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the news at the given index.
   */
  com.google.protobuf.ByteString
      getNewsBytes(int index);
}
