// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

/**
 * Protobuf type {@code com.subscriptionmanager.Newsletter}
 */
public final class Newsletter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.subscriptionmanager.Newsletter)
    NewsletterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Newsletter.newBuilder() to construct.
  private Newsletter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Newsletter() {
    news_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Newsletter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.subscription.proto.Message.internal_static_com_subscriptionmanager_Newsletter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.subscription.proto.Message.internal_static_com_subscriptionmanager_Newsletter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.subscription.proto.Newsletter.class, com.subscription.proto.Newsletter.Builder.class);
  }

  public static final int NEWS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList news_;
  /**
   * <code>repeated string news = 1;</code>
   * @return A list containing the news.
   */
  public com.google.protobuf.ProtocolStringList
      getNewsList() {
    return news_;
  }
  /**
   * <code>repeated string news = 1;</code>
   * @return The count of news.
   */
  public int getNewsCount() {
    return news_.size();
  }
  /**
   * <code>repeated string news = 1;</code>
   * @param index The index of the element to return.
   * @return The news at the given index.
   */
  public java.lang.String getNews(int index) {
    return news_.get(index);
  }
  /**
   * <code>repeated string news = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the news at the given index.
   */
  public com.google.protobuf.ByteString
      getNewsBytes(int index) {
    return news_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < news_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, news_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < news_.size(); i++) {
        dataSize += computeStringSizeNoTag(news_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNewsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.subscription.proto.Newsletter)) {
      return super.equals(obj);
    }
    com.subscription.proto.Newsletter other = (com.subscription.proto.Newsletter) obj;

    if (!getNewsList()
        .equals(other.getNewsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNewsCount() > 0) {
      hash = (37 * hash) + NEWS_FIELD_NUMBER;
      hash = (53 * hash) + getNewsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.subscription.proto.Newsletter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.Newsletter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscription.proto.Newsletter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscription.proto.Newsletter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.subscription.proto.Newsletter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscription.proto.Newsletter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.subscription.proto.Newsletter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.subscriptionmanager.Newsletter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.subscriptionmanager.Newsletter)
      com.subscription.proto.NewsletterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_Newsletter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_Newsletter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subscription.proto.Newsletter.class, com.subscription.proto.Newsletter.Builder.class);
    }

    // Construct using com.subscription.proto.Newsletter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      news_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.subscription.proto.Message.internal_static_com_subscriptionmanager_Newsletter_descriptor;
    }

    @java.lang.Override
    public com.subscription.proto.Newsletter getDefaultInstanceForType() {
      return com.subscription.proto.Newsletter.getDefaultInstance();
    }

    @java.lang.Override
    public com.subscription.proto.Newsletter build() {
      com.subscription.proto.Newsletter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.subscription.proto.Newsletter buildPartial() {
      com.subscription.proto.Newsletter result = new com.subscription.proto.Newsletter(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        news_ = news_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.news_ = news_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.subscription.proto.Newsletter) {
        return mergeFrom((com.subscription.proto.Newsletter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.subscription.proto.Newsletter other) {
      if (other == com.subscription.proto.Newsletter.getDefaultInstance()) return this;
      if (!other.news_.isEmpty()) {
        if (news_.isEmpty()) {
          news_ = other.news_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNewsIsMutable();
          news_.addAll(other.news_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNewsIsMutable();
              news_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList news_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNewsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        news_ = new com.google.protobuf.LazyStringArrayList(news_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string news = 1;</code>
     * @return A list containing the news.
     */
    public com.google.protobuf.ProtocolStringList
        getNewsList() {
      return news_.getUnmodifiableView();
    }
    /**
     * <code>repeated string news = 1;</code>
     * @return The count of news.
     */
    public int getNewsCount() {
      return news_.size();
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param index The index of the element to return.
     * @return The news at the given index.
     */
    public java.lang.String getNews(int index) {
      return news_.get(index);
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the news at the given index.
     */
    public com.google.protobuf.ByteString
        getNewsBytes(int index) {
      return news_.getByteString(index);
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param index The index to set the value at.
     * @param value The news to set.
     * @return This builder for chaining.
     */
    public Builder setNews(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNewsIsMutable();
      news_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param value The news to add.
     * @return This builder for chaining.
     */
    public Builder addNews(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNewsIsMutable();
      news_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param values The news to add.
     * @return This builder for chaining.
     */
    public Builder addAllNews(
        java.lang.Iterable<java.lang.String> values) {
      ensureNewsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, news_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string news = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNews() {
      news_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string news = 1;</code>
     * @param value The bytes of the news to add.
     * @return This builder for chaining.
     */
    public Builder addNewsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNewsIsMutable();
      news_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.subscriptionmanager.Newsletter)
  }

  // @@protoc_insertion_point(class_scope:com.subscriptionmanager.Newsletter)
  private static final com.subscription.proto.Newsletter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.subscription.proto.Newsletter();
  }

  public static com.subscription.proto.Newsletter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Newsletter>
      PARSER = new com.google.protobuf.AbstractParser<Newsletter>() {
    @java.lang.Override
    public Newsletter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Newsletter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Newsletter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.subscription.proto.Newsletter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

