// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.subscription.proto;

public interface RenewSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.subscriptionmanager.RenewSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool renewed = 1;</code>
   * @return The renewed.
   */
  boolean getRenewed();
}
