// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.subscription.proto;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\027com.subscriptionmanager" +
      "\032\rmessage.proto2r\n\025AuthenticationService" +
      "\022Y\n\ncreateUser\022*.com.subscriptionmanager" +
      ".CreateUserRequest\032\035.com.subscriptionman" +
      "ager.User\"\0002h\n\013NewsService\022Y\n\ncreateNews" +
      "\022*.com.subscriptionmanager.CreateNewsReq" +
      "uest\032\035.com.subscriptionmanager.News\"\0002l\n" +
      "\014GenreService\022\\\n\013createGenre\022+.com.subsc" +
      "riptionmanager.CreateGenreRequest\032\036.com." +
      "subscriptionmanager.Genre\"\0002\210\001\n\023Subscrip" +
      "tionService\022q\n\022createSubscription\0222.com." +
      "subscriptionmanager.CreateSubscriptionRe" +
      "quest\032%.com.subscriptionmanager.Subscrip" +
      "tion\"\0002\377\003\n\013UserService\022y\n\020ListSubscripti" +
      "on\0220.com.subscriptionmanager.ListSubscri" +
      "ptionRequest\0321.com.subscriptionmanager.L" +
      "istSubscriptionResponse\"\000\022v\n\017AddSubscrip" +
      "tion\022/.com.subscriptionmanager.AddSubscr" +
      "iptionRequest\0320.com.subscriptionmanager." +
      "AddSubscriptionResponse\"\000\022|\n\021RenewSubscr" +
      "iption\0221.com.subscriptionmanager.RenewSu" +
      "bscriptionRequest\0322.com.subscriptionmana" +
      "ger.RenewSubscriptionResponse\"\000\022\177\n\022Delet" +
      "eSubscription\0222.com.subscriptionmanager." +
      "DeleteSubscriptionRequest\0323.com.subscrip" +
      "tionmanager.DeleteSubscriptionResponse\"\000" +
      "2e\n\021NewsletterService\022P\n\016sendNewsletter\022" +
      "\036.com.subscriptionmanager.Empty\032\036.com.su" +
      "bscriptionmanager.EmptyB\032\n\026com.subscript" +
      "ion.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.subscription.proto.Message.getDescriptor(),
        });
    com.subscription.proto.Message.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
