// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface AddUserSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.AddUserSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.UserSubscription userSubscription = 1;</code>
   * @return Whether the userSubscription field is set.
   */
  boolean hasUserSubscription();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.UserSubscription userSubscription = 1;</code>
   * @return The userSubscription.
   */
  com.subscriptionmanager.v1.proto.UserSubscription getUserSubscription();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.UserSubscription userSubscription = 1;</code>
   */
  com.subscriptionmanager.v1.proto.UserSubscriptionOrBuilder getUserSubscriptionOrBuilder();
}
