// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface CreateGenreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.CreateGenreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The parent resource where this genre will be created.
   * Format: subscriptions/{subscription}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The parent resource where this genre will be created.
   * Format: subscriptions/{subscription}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   *The genre to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Genre genre = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the genre field is set.
   */
  boolean hasGenre();
  /**
   * <pre>
   *The genre to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Genre genre = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The genre.
   */
  com.subscriptionmanager.v1.proto.Genre getGenre();
  /**
   * <pre>
   *The genre to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Genre genre = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.subscriptionmanager.v1.proto.GenreOrBuilder getGenreOrBuilder();
}
