// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface CreateSubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.CreateSubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The subscription to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the subscription field is set.
   */
  boolean hasSubscription();
  /**
   * <pre>
   *The subscription to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The subscription.
   */
  com.subscriptionmanager.v1.proto.Subscription getSubscription();
  /**
   * <pre>
   *The subscription to create
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.subscriptionmanager.v1.proto.SubscriptionOrBuilder getSubscriptionOrBuilder();
}
