// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface ListSubscriptionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.ListSubscriptionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>repeated .subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  java.util.List<com.subscriptionmanager.v1.proto.Subscription> 
      getSubscriptionList();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>repeated .subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  com.subscriptionmanager.v1.proto.Subscription getSubscription(int index);
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>repeated .subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  int getSubscriptionCount();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>repeated .subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  java.util.List<? extends com.subscriptionmanager.v1.proto.SubscriptionOrBuilder> 
      getSubscriptionOrBuilderList();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>repeated .subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  com.subscriptionmanager.v1.proto.SubscriptionOrBuilder getSubscriptionOrBuilder(
      int index);
}
