// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface ListSubscriptionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.ListSubscriptionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The parent, which owns this collection of subscription.
   * Format: users/{user}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The parent, which owns this collection of subscription.
   * Format: users/{user}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();
}
