// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_News_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_News_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_CreateNewsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_CreateNewsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_Genre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_Genre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_CreateGenreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_CreateGenreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_CreateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_CreateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_ListSubscriptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_ListSubscriptionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_AddSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_AddSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_RenewSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_Newsletter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_Newsletter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptionmanager_v1_proto_NewsletterMailInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptionmanager_v1_proto_NewsletterMailInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*subscriptionmanager/v1/proto/message.p" +
      "roto\022\034subscriptionmanager.v1.proto\032\037goog" +
      "le/api/field_behavior.proto\032\026google/type" +
      "/date.proto\"\334\001\n\004User\022\021\n\004name\030\001 \001(\tB\003\340A\003\022" +
      "\031\n\014display_name\030\002 \001(\tB\003\340A\002\022\025\n\010email_id\030\003" +
      " \001(\tB\003\340A\002\022\025\n\010password\030\004 \001(\tB\003\340A\002\022:\n\004role" +
      "\030\005 \001(\0162\'.subscriptionmanager.v1.proto.Us" +
      "er.RoleB\003\340A\002\"<\n\004Role\022\024\n\020ROLE_UNSPECIFIED" +
      "\020\000\022\r\n\tROLE_USER\020\001\022\017\n\013ROLE_WRITER\020\002\"J\n\021Cr" +
      "eateUserRequest\0225\n\004user\030\001 \001(\0132\".subscrip" +
      "tionmanager.v1.proto.UserB\003\340A\002\"G\n\004News\022\021" +
      "\n\004name\030\001 \001(\tB\003\340A\003\022\022\n\005title\030\002 \001(\tB\003\340A\002\022\030\n" +
      "\013description\030\003 \001(\tB\003\340A\002\"_\n\021CreateNewsReq" +
      "uest\022\023\n\006parent\030\001 \001(\tB\003\340A\002\0225\n\004news\030\002 \001(\0132" +
      "\".subscriptionmanager.v1.proto.NewsB\003\340A\002" +
      "\"5\n\005Genre\022\021\n\004name\030\001 \001(\tB\003\340A\003\022\031\n\014display_" +
      "name\030\002 \001(\tB\003\340A\002\"b\n\022CreateGenreRequest\022\023\n" +
      "\006parent\030\001 \001(\tB\003\340A\002\0227\n\005genre\030\002 \001(\0132#.subs" +
      "criptionmanager.v1.proto.GenreB\003\340A\002\"g\n\014S" +
      "ubscription\022\021\n\004name\030\001 \001(\tB\003\340A\003\022\031\n\014displa" +
      "y_name\030\002 \001(\tB\003\340A\002\022\022\n\005price\030\003 \001(\005B\003\340A\002\022\025\n" +
      "\010validity\030\004 \001(\005B\003\340A\002\"b\n\031CreateSubscripti" +
      "onRequest\022E\n\014subscription\030\001 \001(\0132*.subscr" +
      "iptionmanager.v1.proto.SubscriptionB\003\340A\002" +
      "\"V\n\030ListSubscriptionsRequest\022\023\n\006parent\030\001" +
      " \001(\tB\003\340A\002\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_tok" +
      "en\030\003 \001(\t\"v\n\031ListSubscriptionsResponse\022@\n" +
      "\014subscription\030\001 \003(\0132*.subscriptionmanage" +
      "r.v1.proto.Subscription\022\027\n\017next_page_tok" +
      "en\030\002 \001(\t\"@\n\026AddSubscriptionRequest\022\023\n\006pa" +
      "rent\030\001 \001(\tB\003\340A\002\022\021\n\004name\030\002 \001(\tB\003\340A\002\"\203\001\n\027A" +
      "ddSubscriptionResponse\022@\n\014subscription\030\001" +
      " \001(\0132*.subscriptionmanager.v1.proto.Subs" +
      "cription\022&\n\013expiry_date\030\002 \001(\0132\021.google.t" +
      "ype.Date\"C\n\031RemoveSubscriptionRequest\022\023\n" +
      "\006parent\030\001 \001(\tB\003\340A\002\022\021\n\004name\030\002 \001(\tB\003\340A\002\"^\n" +
      "\032RemoveSubscriptionResponse\022@\n\014subscript" +
      "ion\030\001 \001(\0132*.subscriptionmanager.v1.proto" +
      ".Subscription\"B\n\030RenewSubscriptionReques" +
      "t\022\023\n\006parent\030\001 \001(\tB\003\340A\002\022\021\n\004name\030\002 \001(\tB\003\340A" +
      "\002\"\205\001\n\031RenewSubscriptionResponse\022@\n\014subsc" +
      "ription\030\001 \001(\0132*.subscriptionmanager.v1.p" +
      "roto.Subscription\022&\n\013expiry_date\030\002 \001(\0132\021" +
      ".google.type.Date\"\037\n\nNewsletter\022\021\n\004news\030" +
      "\001 \003(\tB\003\340A\002\"n\n\022NewsletterMailInfo\022A\n\nnews" +
      "letter\030\001 \001(\0132(.subscriptionmanager.v1.pr" +
      "oto.NewsletterB\003\340A\002\022\025\n\010email_id\030\002 \003(\tB\003\340" +
      "A\002B2\n com.subscriptionmanager.v1.protoB\014" +
      "MessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
        });
    internal_static_subscriptionmanager_v1_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_subscriptionmanager_v1_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_User_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "EmailId", "Password", "Role", });
    internal_static_subscriptionmanager_v1_proto_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_subscriptionmanager_v1_proto_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_CreateUserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_subscriptionmanager_v1_proto_News_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_subscriptionmanager_v1_proto_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_News_descriptor,
        new java.lang.String[] { "Name", "Title", "Description", });
    internal_static_subscriptionmanager_v1_proto_CreateNewsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_subscriptionmanager_v1_proto_CreateNewsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_CreateNewsRequest_descriptor,
        new java.lang.String[] { "Parent", "News", });
    internal_static_subscriptionmanager_v1_proto_Genre_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_subscriptionmanager_v1_proto_Genre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_Genre_descriptor,
        new java.lang.String[] { "Name", "DisplayName", });
    internal_static_subscriptionmanager_v1_proto_CreateGenreRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_subscriptionmanager_v1_proto_CreateGenreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_CreateGenreRequest_descriptor,
        new java.lang.String[] { "Parent", "Genre", });
    internal_static_subscriptionmanager_v1_proto_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_subscriptionmanager_v1_proto_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_Subscription_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "Price", "Validity", });
    internal_static_subscriptionmanager_v1_proto_CreateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_subscriptionmanager_v1_proto_CreateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_CreateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_ListSubscriptionsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_subscriptionmanager_v1_proto_ListSubscriptionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_ListSubscriptionsResponse_descriptor,
        new java.lang.String[] { "Subscription", "NextPageToken", });
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_AddSubscriptionRequest_descriptor,
        new java.lang.String[] { "Parent", "Name", });
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_subscriptionmanager_v1_proto_AddSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_AddSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscription", "ExpiryDate", });
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionRequest_descriptor,
        new java.lang.String[] { "Parent", "Name", });
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_RemoveSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscription", });
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_RenewSubscriptionRequest_descriptor,
        new java.lang.String[] { "Parent", "Name", });
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor,
        new java.lang.String[] { "Subscription", "ExpiryDate", });
    internal_static_subscriptionmanager_v1_proto_Newsletter_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_subscriptionmanager_v1_proto_Newsletter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_Newsletter_descriptor,
        new java.lang.String[] { "News", });
    internal_static_subscriptionmanager_v1_proto_NewsletterMailInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_subscriptionmanager_v1_proto_NewsletterMailInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptionmanager_v1_proto_NewsletterMailInfo_descriptor,
        new java.lang.String[] { "Newsletter", "EmailId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
