// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface NewsletterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.Newsletter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The news from the specified subscription.
   * </pre>
   *
   * <code>repeated string news = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return A list containing the news.
   */
  java.util.List<java.lang.String>
      getNewsList();
  /**
   * <pre>
   * The news from the specified subscription.
   * </pre>
   *
   * <code>repeated string news = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The count of news.
   */
  int getNewsCount();
  /**
   * <pre>
   * The news from the specified subscription.
   * </pre>
   *
   * <code>repeated string news = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the element to return.
   * @return The news at the given index.
   */
  java.lang.String getNews(int index);
  /**
   * <pre>
   * The news from the specified subscription.
   * </pre>
   *
   * <code>repeated string news = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the value to return.
   * @return The bytes of the news at the given index.
   */
  com.google.protobuf.ByteString
      getNewsBytes(int index);
}
