// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface RemoveSubscriptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.RemoveSubscriptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   * @return Whether the subscription field is set.
   */
  boolean hasSubscription();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   * @return The subscription.
   */
  com.subscriptionmanager.v1.proto.Subscription getSubscription();
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  com.subscriptionmanager.v1.proto.SubscriptionOrBuilder getSubscriptionOrBuilder();
}
