// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

/**
 * <pre>
 *Response of renewing subscription
 * </pre>
 *
 * Protobuf type {@code subscriptionmanager.v1.proto.RenewSubscriptionResponse}
 */
public final class RenewSubscriptionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:subscriptionmanager.v1.proto.RenewSubscriptionResponse)
    RenewSubscriptionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RenewSubscriptionResponse.newBuilder() to construct.
  private RenewSubscriptionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenewSubscriptionResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RenewSubscriptionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.subscriptionmanager.v1.proto.MessageProto.internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.subscriptionmanager.v1.proto.MessageProto.internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.class, com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.Builder.class);
  }

  public static final int SUBSCRIPTION_FIELD_NUMBER = 1;
  private com.subscriptionmanager.v1.proto.Subscription subscription_;
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   * @return Whether the subscription field is set.
   */
  @java.lang.Override
  public boolean hasSubscription() {
    return subscription_ != null;
  }
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   * @return The subscription.
   */
  @java.lang.Override
  public com.subscriptionmanager.v1.proto.Subscription getSubscription() {
    return subscription_ == null ? com.subscriptionmanager.v1.proto.Subscription.getDefaultInstance() : subscription_;
  }
  /**
   * <pre>
   * The subscriptions from the specified user.
   * </pre>
   *
   * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
   */
  @java.lang.Override
  public com.subscriptionmanager.v1.proto.SubscriptionOrBuilder getSubscriptionOrBuilder() {
    return getSubscription();
  }

  public static final int EXPIRY_DATE_FIELD_NUMBER = 2;
  private com.google.type.Date expiryDate_;
  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 2;</code>
   * @return Whether the expiryDate field is set.
   */
  @java.lang.Override
  public boolean hasExpiryDate() {
    return expiryDate_ != null;
  }
  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 2;</code>
   * @return The expiryDate.
   */
  @java.lang.Override
  public com.google.type.Date getExpiryDate() {
    return expiryDate_ == null ? com.google.type.Date.getDefaultInstance() : expiryDate_;
  }
  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 2;</code>
   */
  @java.lang.Override
  public com.google.type.DateOrBuilder getExpiryDateOrBuilder() {
    return getExpiryDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subscription_ != null) {
      output.writeMessage(1, getSubscription());
    }
    if (expiryDate_ != null) {
      output.writeMessage(2, getExpiryDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (subscription_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSubscription());
    }
    if (expiryDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExpiryDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.subscriptionmanager.v1.proto.RenewSubscriptionResponse)) {
      return super.equals(obj);
    }
    com.subscriptionmanager.v1.proto.RenewSubscriptionResponse other = (com.subscriptionmanager.v1.proto.RenewSubscriptionResponse) obj;

    if (hasSubscription() != other.hasSubscription()) return false;
    if (hasSubscription()) {
      if (!getSubscription()
          .equals(other.getSubscription())) return false;
    }
    if (hasExpiryDate() != other.hasExpiryDate()) return false;
    if (hasExpiryDate()) {
      if (!getExpiryDate()
          .equals(other.getExpiryDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSubscription()) {
      hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getSubscription().hashCode();
    }
    if (hasExpiryDate()) {
      hash = (37 * hash) + EXPIRY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpiryDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.subscriptionmanager.v1.proto.RenewSubscriptionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Response of renewing subscription
   * </pre>
   *
   * Protobuf type {@code subscriptionmanager.v1.proto.RenewSubscriptionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:subscriptionmanager.v1.proto.RenewSubscriptionResponse)
      com.subscriptionmanager.v1.proto.RenewSubscriptionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.subscriptionmanager.v1.proto.MessageProto.internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.subscriptionmanager.v1.proto.MessageProto.internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.class, com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.Builder.class);
    }

    // Construct using com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (subscriptionBuilder_ == null) {
        subscription_ = null;
      } else {
        subscription_ = null;
        subscriptionBuilder_ = null;
      }
      if (expiryDateBuilder_ == null) {
        expiryDate_ = null;
      } else {
        expiryDate_ = null;
        expiryDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.subscriptionmanager.v1.proto.MessageProto.internal_static_subscriptionmanager_v1_proto_RenewSubscriptionResponse_descriptor;
    }

    @java.lang.Override
    public com.subscriptionmanager.v1.proto.RenewSubscriptionResponse getDefaultInstanceForType() {
      return com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.subscriptionmanager.v1.proto.RenewSubscriptionResponse build() {
      com.subscriptionmanager.v1.proto.RenewSubscriptionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.subscriptionmanager.v1.proto.RenewSubscriptionResponse buildPartial() {
      com.subscriptionmanager.v1.proto.RenewSubscriptionResponse result = new com.subscriptionmanager.v1.proto.RenewSubscriptionResponse(this);
      if (subscriptionBuilder_ == null) {
        result.subscription_ = subscription_;
      } else {
        result.subscription_ = subscriptionBuilder_.build();
      }
      if (expiryDateBuilder_ == null) {
        result.expiryDate_ = expiryDate_;
      } else {
        result.expiryDate_ = expiryDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.subscriptionmanager.v1.proto.RenewSubscriptionResponse) {
        return mergeFrom((com.subscriptionmanager.v1.proto.RenewSubscriptionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.subscriptionmanager.v1.proto.RenewSubscriptionResponse other) {
      if (other == com.subscriptionmanager.v1.proto.RenewSubscriptionResponse.getDefaultInstance()) return this;
      if (other.hasSubscription()) {
        mergeSubscription(other.getSubscription());
      }
      if (other.hasExpiryDate()) {
        mergeExpiryDate(other.getExpiryDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSubscriptionFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getExpiryDateFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.subscriptionmanager.v1.proto.Subscription subscription_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.subscriptionmanager.v1.proto.Subscription, com.subscriptionmanager.v1.proto.Subscription.Builder, com.subscriptionmanager.v1.proto.SubscriptionOrBuilder> subscriptionBuilder_;
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     * @return Whether the subscription field is set.
     */
    public boolean hasSubscription() {
      return subscriptionBuilder_ != null || subscription_ != null;
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     * @return The subscription.
     */
    public com.subscriptionmanager.v1.proto.Subscription getSubscription() {
      if (subscriptionBuilder_ == null) {
        return subscription_ == null ? com.subscriptionmanager.v1.proto.Subscription.getDefaultInstance() : subscription_;
      } else {
        return subscriptionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public Builder setSubscription(com.subscriptionmanager.v1.proto.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subscription_ = value;
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public Builder setSubscription(
        com.subscriptionmanager.v1.proto.Subscription.Builder builderForValue) {
      if (subscriptionBuilder_ == null) {
        subscription_ = builderForValue.build();
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public Builder mergeSubscription(com.subscriptionmanager.v1.proto.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (subscription_ != null) {
          subscription_ =
            com.subscriptionmanager.v1.proto.Subscription.newBuilder(subscription_).mergeFrom(value).buildPartial();
        } else {
          subscription_ = value;
        }
        onChanged();
      } else {
        subscriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public Builder clearSubscription() {
      if (subscriptionBuilder_ == null) {
        subscription_ = null;
        onChanged();
      } else {
        subscription_ = null;
        subscriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public com.subscriptionmanager.v1.proto.Subscription.Builder getSubscriptionBuilder() {
      
      onChanged();
      return getSubscriptionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    public com.subscriptionmanager.v1.proto.SubscriptionOrBuilder getSubscriptionOrBuilder() {
      if (subscriptionBuilder_ != null) {
        return subscriptionBuilder_.getMessageOrBuilder();
      } else {
        return subscription_ == null ?
            com.subscriptionmanager.v1.proto.Subscription.getDefaultInstance() : subscription_;
      }
    }
    /**
     * <pre>
     * The subscriptions from the specified user.
     * </pre>
     *
     * <code>.subscriptionmanager.v1.proto.Subscription subscription = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.subscriptionmanager.v1.proto.Subscription, com.subscriptionmanager.v1.proto.Subscription.Builder, com.subscriptionmanager.v1.proto.SubscriptionOrBuilder> 
        getSubscriptionFieldBuilder() {
      if (subscriptionBuilder_ == null) {
        subscriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.subscriptionmanager.v1.proto.Subscription, com.subscriptionmanager.v1.proto.Subscription.Builder, com.subscriptionmanager.v1.proto.SubscriptionOrBuilder>(
                getSubscription(),
                getParentForChildren(),
                isClean());
        subscription_ = null;
      }
      return subscriptionBuilder_;
    }

    private com.google.type.Date expiryDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> expiryDateBuilder_;
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     * @return Whether the expiryDate field is set.
     */
    public boolean hasExpiryDate() {
      return expiryDateBuilder_ != null || expiryDate_ != null;
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     * @return The expiryDate.
     */
    public com.google.type.Date getExpiryDate() {
      if (expiryDateBuilder_ == null) {
        return expiryDate_ == null ? com.google.type.Date.getDefaultInstance() : expiryDate_;
      } else {
        return expiryDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public Builder setExpiryDate(com.google.type.Date value) {
      if (expiryDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiryDate_ = value;
        onChanged();
      } else {
        expiryDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public Builder setExpiryDate(
        com.google.type.Date.Builder builderForValue) {
      if (expiryDateBuilder_ == null) {
        expiryDate_ = builderForValue.build();
        onChanged();
      } else {
        expiryDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public Builder mergeExpiryDate(com.google.type.Date value) {
      if (expiryDateBuilder_ == null) {
        if (expiryDate_ != null) {
          expiryDate_ =
            com.google.type.Date.newBuilder(expiryDate_).mergeFrom(value).buildPartial();
        } else {
          expiryDate_ = value;
        }
        onChanged();
      } else {
        expiryDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public Builder clearExpiryDate() {
      if (expiryDateBuilder_ == null) {
        expiryDate_ = null;
        onChanged();
      } else {
        expiryDate_ = null;
        expiryDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public com.google.type.Date.Builder getExpiryDateBuilder() {
      
      onChanged();
      return getExpiryDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    public com.google.type.DateOrBuilder getExpiryDateOrBuilder() {
      if (expiryDateBuilder_ != null) {
        return expiryDateBuilder_.getMessageOrBuilder();
      } else {
        return expiryDate_ == null ?
            com.google.type.Date.getDefaultInstance() : expiryDate_;
      }
    }
    /**
     * <pre>
     *expiry date
     * </pre>
     *
     * <code>.google.type.Date expiry_date = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> 
        getExpiryDateFieldBuilder() {
      if (expiryDateBuilder_ == null) {
        expiryDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder>(
                getExpiryDate(),
                getParentForChildren(),
                isClean());
        expiryDate_ = null;
      }
      return expiryDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:subscriptionmanager.v1.proto.RenewSubscriptionResponse)
  }

  // @@protoc_insertion_point(class_scope:subscriptionmanager.v1.proto.RenewSubscriptionResponse)
  private static final com.subscriptionmanager.v1.proto.RenewSubscriptionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.subscriptionmanager.v1.proto.RenewSubscriptionResponse();
  }

  public static com.subscriptionmanager.v1.proto.RenewSubscriptionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenewSubscriptionResponse>
      PARSER = new com.google.protobuf.AbstractParser<RenewSubscriptionResponse>() {
    @java.lang.Override
    public RenewSubscriptionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RenewSubscriptionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenewSubscriptionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.subscriptionmanager.v1.proto.RenewSubscriptionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

