// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The unique identification id of the subscription
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *The unique identification id of the subscription
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *The name of the subscription which would be displayed
   * </pre>
   *
   * <code>string display_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   *The name of the subscription which would be displayed
   * </pre>
   *
   * <code>string display_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   *The price of the subscription
   * </pre>
   *
   * <code>int32 price = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <pre>
   *The validity of the subscription in no of days
   * </pre>
   *
   * <code>int32 validity = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The validity.
   */
  int getValidity();
}
