// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/message.proto

package com.subscriptionmanager.v1.proto;

public interface UserSubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subscriptionmanager.v1.proto.UserSubscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The unique identification id of the subscription
   *Format subscription/{subscriptionId}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *The unique identification id of the subscription
   *Format subscription/{subscriptionId}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *The name of the subscription which would be displayed
   * </pre>
   *
   * <code>string display_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   *The name of the subscription which would be displayed
   * </pre>
   *
   * <code>string display_name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 3;</code>
   * @return Whether the expiryDate field is set.
   */
  boolean hasExpiryDate();
  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 3;</code>
   * @return The expiryDate.
   */
  com.google.type.Date getExpiryDate();
  /**
   * <pre>
   *expiry date
   * </pre>
   *
   * <code>.google.type.Date expiry_date = 3;</code>
   */
  com.google.type.DateOrBuilder getExpiryDateOrBuilder();
}
