// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/service.proto

package com.subscription.v1.proto;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*subscriptionmanager/v1/proto/service.p" +
      "roto\022\034subscriptionmanager.v1.proto\032\034goog" +
      "le/api/annotations.proto\032\027google/api/cli" +
      "ent.proto\032\037google/api/field_behavior.pro" +
      "to\032\031google/api/resource.proto\032\036google/pr" +
      "otobuf/duration.proto\032\033google/protobuf/e" +
      "mpty.proto\032*subscriptionmanager/v1/proto" +
      "/message.proto2\232\001\n\025AuthenticationService" +
      "\022\200\001\n\ncreateUser\022/.subscriptionmanager.v1" +
      ".proto.CreateUserRequest\032\".subscriptionm" +
      "anager.v1.proto.User\"\035\202\323\344\223\002\020\"\010v1/users:\004" +
      "user\332A\004user2\251\001\n\013NewsService\022\231\001\n\ncreateNe" +
      "ws\022/.subscriptionmanager.v1.proto.Create" +
      "NewsRequest\032\".subscriptionmanager.v1.pro" +
      "to.News\"6\202\323\344\223\002\"\"\032/v1/{parent=genres/*}/n" +
      "ews:\004news\332A\013parent,news2\270\001\n\014GenreService" +
      "\022\247\001\n\013createGenre\0220.subscriptionmanager.v" +
      "1.proto.CreateGenreRequest\032#.subscriptio" +
      "nmanager.v1.proto.Genre\"A\202\323\344\223\002,\"#/v1/{pa" +
      "rent=subscriptions/*}/genres:\005genre\332A\014pa" +
      "rent,genre2\310\001\n\023SubscriptionService\022\260\001\n\022c" +
      "reateSubscription\0227.subscriptionmanager." +
      "v1.proto.CreateSubscriptionRequest\032*.sub" +
      "scriptionmanager.v1.proto.Subscription\"5" +
      "\202\323\344\223\002 \"\020v1/subscriptions:\014subscription\332A" +
      "\014subscription2\330\006\n\013UserService\022\267\001\n\020ListSu" +
      "bscription\0226.subscriptionmanager.v1.prot" +
      "o.ListSubscriptionsRequest\0327.subscriptio" +
      "nmanager.v1.proto.ListSubscriptionsRespo" +
      "nse\"2\202\323\344\223\002#\022!v1/{parent=users/*}/subscri" +
      "ptions\332A\006parent\022\323\001\n\017AddSubscription\0224.su" +
      "bscriptionmanager.v1.proto.AddSubscripti" +
      "onRequest\0325.subscriptionmanager.v1.proto" +
      ".AddSubscriptionResponse\"S\202\323\344\223\0024\"!v1/{pa" +
      "rent=users/*}/subscriptions:\017subscriptio" +
      "n_id\332A\026parent,subscription_id\022\331\001\n\021RenewS" +
      "ubscription\0226.subscriptionmanager.v1.pro" +
      "to.RenewSubscriptionRequest\0327.subscripti" +
      "onmanager.v1.proto.RenewSubscriptionResp" +
      "onse\"S\202\323\344\223\0024\"!v1/{parent=users/*}/subscr" +
      "iptions:\017subscription_id\332A\026parent,subscr" +
      "iption_id\022\334\001\n\022RemoveSubscription\0227.subsc" +
      "riptionmanager.v1.proto.RemoveSubscripti" +
      "onRequest\0328.subscriptionmanager.v1.proto" +
      ".RemoveSubscriptionResponse\"S\202\323\344\223\0024\"!v1/" +
      "{parent=users/*}/subscriptions:\017subscrip" +
      "tion_id\332A\026parent,subscription_idB\035\n\031com." +
      "subscription.v1.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.subscriptionmanager.v1.proto.MessageProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.subscriptionmanager.v1.proto.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
