// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/service.proto

package com.subscription.v1.proto;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*subscriptionmanager/v1/proto/service.p" +
      "roto\022\034subscriptionmanager.v1.proto\032\034goog" +
      "le/api/annotations.proto\032\027google/api/cli" +
      "ent.proto\032\037google/api/field_behavior.pro" +
      "to\032\031google/api/resource.proto\032\036google/pr" +
      "otobuf/duration.proto\032\033google/protobuf/e" +
      "mpty.proto\032*subscriptionmanager/v1/proto" +
      "/message.proto2\242\001\n\025AuthenticationService" +
      "\022\210\001\n\ncreateUser\022/.subscriptionmanager.v1" +
      ".proto.CreateUserRequest\032\".subscriptionm" +
      "anager.v1.proto.User\"%\202\323\344\223\002\030\"\020/v1/users:" +
      "create:\004user\332A\004user2\260\001\n\013NewsService\022\240\001\n\n" +
      "createNews\022/.subscriptionmanager.v1.prot" +
      "o.CreateNewsRequest\032\".subscriptionmanage" +
      "r.v1.proto.News\"=\202\323\344\223\002)\"!/v1/{parent=gen" +
      "res/*}/news:create:\004news\332A\013parent,news2\276" +
      "\001\n\014GenreService\022\255\001\n\013createGenre\0220.subscr" +
      "iptionmanager.v1.proto.CreateGenreReques" +
      "t\032#.subscriptionmanager.v1.proto.Genre\"G" +
      "\202\323\344\223\0022\")/v1/{parent=subscriptions/*}/gen" +
      "re:create:\005genre\332A\014parent,genre2\320\001\n\023Subs" +
      "criptionService\022\270\001\n\022createSubscription\0227" +
      ".subscriptionmanager.v1.proto.CreateSubs" +
      "criptionRequest\032*.subscriptionmanager.v1" +
      ".proto.Subscription\"=\202\323\344\223\002(\"\030/v1/subscri" +
      "ptions:create:\014subscription\332A\014subscripti" +
      "on2\302\006\n\013UserService\022\305\001\n\025ListUserSubscript" +
      "ions\022:.subscriptionmanager.v1.proto.List" +
      "UserSubscriptionsRequest\032;.subscriptionm" +
      "anager.v1.proto.ListUserSubscriptionsRes" +
      "ponse\"3\202\323\344\223\002$\022\"/v1/{parent=users/*}/subs" +
      "criptions\332A\006parent\022\313\001\n\023AddUserSubscripti" +
      "on\0228.subscriptionmanager.v1.proto.AddUse" +
      "rSubscriptionRequest\0329.subscriptionmanag" +
      "er.v1.proto.AddUserSubscriptionResponse\"" +
      "?\202\323\344\223\002+\"&/v1/{parent=users/*}/subscripti" +
      "ons:add:\001*\332A\013parent,name\022\323\001\n\025RenewUserSu" +
      "bscription\022:.subscriptionmanager.v1.prot" +
      "o.RenewUserSubscriptionRequest\032;.subscri" +
      "ptionmanager.v1.proto.RenewUserSubscript" +
      "ionResponse\"A\202\323\344\223\002-2(/v1/{parent=users/*" +
      "}/subscriptions:renew:\001*\332A\013parent,name\022\306" +
      "\001\n\026RemoveUserSubscription\022;.subscription" +
      "manager.v1.proto.RemoveUserSubscriptionR" +
      "equest\032<.subscriptionmanager.v1.proto.Re" +
      "moveUserSubscriptionResponse\"1\202\323\344\223\002$*\"/v" +
      "1/{name=users/*/subscriptions/*}\332A\004nameB" +
      "+\n\031com.subscription.v1.protoB\014ServicePro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.subscriptionmanager.v1.proto.MessageProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.subscriptionmanager.v1.proto.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
