// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptionmanager/v1/proto/service.proto

package com.subscription.v1.proto;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*subscriptionmanager/v1/proto/service.p" +
      "roto\022\034subscriptionmanager.v1.proto\032\034goog" +
      "le/api/annotations.proto\032\027google/api/cli" +
      "ent.proto\032\037google/api/field_behavior.pro" +
      "to\032\031google/api/resource.proto\032\036google/pr" +
      "otobuf/duration.proto\032\033google/protobuf/e" +
      "mpty.proto\032*subscriptionmanager/v1/proto" +
      "/message.proto2\233\001\n\025AuthenticationService" +
      "\022\201\001\n\ncreateUser\022/.subscriptionmanager.v1" +
      ".proto.CreateUserRequest\032\".subscriptionm" +
      "anager.v1.proto.User\"\036\202\323\344\223\002\021\"\t/v1/users:" +
      "\004user\332A\004user2\251\001\n\013NewsService\022\231\001\n\ncreateN" +
      "ews\022/.subscriptionmanager.v1.proto.Creat" +
      "eNewsRequest\032\".subscriptionmanager.v1.pr" +
      "oto.News\"6\202\323\344\223\002\"\"\032/v1/{parent=genres/*}/" +
      "news:\004news\332A\013parent,news2\267\001\n\014GenreServic" +
      "e\022\246\001\n\013createGenre\0220.subscriptionmanager." +
      "v1.proto.CreateGenreRequest\032#.subscripti" +
      "onmanager.v1.proto.Genre\"@\202\323\344\223\002+\"\"/v1/{p" +
      "arent=subscriptions/*}/genre:\005genre\332A\014pa" +
      "rent,genre2\311\001\n\023SubscriptionService\022\261\001\n\022c" +
      "reateSubscription\0227.subscriptionmanager." +
      "v1.proto.CreateSubscriptionRequest\032*.sub" +
      "scriptionmanager.v1.proto.Subscription\"6" +
      "\202\323\344\223\002!\"\021/v1/subscriptions:\014subscription\332" +
      "A\014subscription2\316\006\n\027UserSubscriptionServi" +
      "ce\022\305\001\n\025ListUserSubscriptions\022:.subscript" +
      "ionmanager.v1.proto.ListUserSubscription" +
      "sRequest\032;.subscriptionmanager.v1.proto." +
      "ListUserSubscriptionsResponse\"3\202\323\344\223\002$\022\"/" +
      "v1/{parent=users/*}/subscriptions\332A\006pare" +
      "nt\022\313\001\n\023AddUserSubscription\0228.subscriptio" +
      "nmanager.v1.proto.AddUserSubscriptionReq" +
      "uest\0329.subscriptionmanager.v1.proto.AddU" +
      "serSubscriptionResponse\"?\202\323\344\223\002+\"&/v1/{pa" +
      "rent=users/*}/subscriptions:add:\001*\332A\013par" +
      "ent,name\022\323\001\n\025RenewUserSubscription\022:.sub" +
      "scriptionmanager.v1.proto.RenewUserSubsc" +
      "riptionRequest\032;.subscriptionmanager.v1." +
      "proto.RenewUserSubscriptionResponse\"A\202\323\344" +
      "\223\002-2(/v1/{parent=users/*}/subscriptions:" +
      "renew:\001*\332A\013parent,name\022\306\001\n\026RemoveUserSub" +
      "scription\022;.subscriptionmanager.v1.proto" +
      ".RemoveUserSubscriptionRequest\032<.subscri" +
      "ptionmanager.v1.proto.RemoveUserSubscrip" +
      "tionResponse\"1\202\323\344\223\002$*\"/v1/{name=users/*/" +
      "subscriptions/*}\332A\004nameB+\n\031com.subscript" +
      "ion.v1.protoB\014ServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.subscriptionmanager.v1.proto.MessageProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.subscriptionmanager.v1.proto.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
